"""Compose NGINX data-plane configuration from canonical services."""
from __future__ import annotations

from gateway.adapters import default_registry
from gateway.model import normalize_config


def render(config: dict) -> str:
    canonical = normalize_config(config)
    registry = default_registry()
    http_servers: list[str] = []
    stream_formats: list[str] = []
    stream_servers: list[str] = []
    for service in canonical["services"]:
        adapter = registry.get(service["adapter"])
        adapter.validate(service)
        if adapter.plane == "http":
            http_servers.append(adapter.render(service))
        else:
            stream_formats.append(adapter.render_log_format(service))
            stream_servers.append(adapter.render(service))
    resolver = canonical["defaults"]["dns_resolver"]
    output = f'''# Generated by PQC Gateway Framework v3.2. Do not edit.
worker_processes auto;
pid /tmp/nginx.pid;

events {{
    worker_connections 16384;
    multi_accept on;
}}

http {{
    include /opt/nginx/conf/mime.types;
    default_type application/octet-stream;
    log_format pq_access escape=json
        '{{'
        '"ts":"$time_iso8601",'
        '"protocol_type":"http",'
        '"application_protocol":"$pq_application_protocol",'
        '"service":"$pq_service_name",'
        '"configured_groups":"$pq_configured_groups",'
        '"server_name":"$server_name",'
        '"server_port":$server_port,'
        '"remote_addr":"$remote_addr",'
        '"request_id":"$request_id",'
        '"method":"$request_method",'
        '"uri":"$request_uri",'
        '"status":$status,'
        '"bytes_sent":$bytes_sent,'
        '"request_time":$request_time,'
        '"upstream_addr":"$upstream_addr",'
        '"upstream_status":"$upstream_status",'
        '"upstream_response_time":"$upstream_response_time",'
        '"ssl_protocol":"$ssl_protocol",'
        '"ssl_cipher":"$ssl_cipher",'
        '"ssl_curve":"$ssl_curve",'
        '"ssl_server_name":"$ssl_server_name",'
        '"client_verify":"$ssl_client_verify"'
        '}}';
    access_log /var/log/nginx/access.log pq_access;
    error_log /var/log/nginx/error.log info;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65s;
    server_tokens off;
    resolver {resolver} valid=30s ipv6=off;

    server {{
        listen 127.0.0.1:18081;
        server_name _;
        location = /nginx_status {{
            stub_status;
            access_log off;
        }}
    }}
{''.join(http_servers)}
}}
'''
    if stream_servers:
        output += f'''
stream {{
    resolver {resolver} valid=30s ipv6=off;
{''.join(stream_formats)}
{''.join(stream_servers)}
}}
'''
    return output
