"""Enterprise onboarding helpers for the v3.7 API-first deployment profile."""
from __future__ import annotations

import json
import os
import secrets
import shlex
from pathlib import Path
from urllib.parse import urlsplit

from gateway.model import normalize_config


DEFAULT_CONFIG = Path("config/enterprise/services.json")
DEFAULT_ENV = Path(".env.enterprise")
ENTERPRISE_DEFAULTS = {
    "certificate": "/etc/pq-gateway/certs/server.crt",
    "certificate_key": "/etc/pq-gateway/certs/server.key",
    "client_ca": "/etc/pq-gateway/certs/ca.crt",
    "upstream_ca": "/etc/ssl/certs/ca-certificates.crt",
    "dns_resolver": "127.0.0.1",
    "connect_timeout": "5s",
    "send_timeout": "60s",
    "read_timeout": "60s",
}


def _quoted(value: object) -> str:
    return shlex.quote(str(value))


def load_env(path: str | Path) -> dict[str, str]:
    result: dict[str, str] = {}
    source = Path(path)
    if not source.exists():
        return result
    for raw in source.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        parts = shlex.split(value, comments=False, posix=True)
        result[key.strip()] = parts[0] if parts else ""
    return result


def write_env(path: str | Path, values: dict[str, object]) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by pqctl onboard. Keep this file out of version control.",
        *[f"{key}={_quoted(value)}" for key, value in sorted(values.items())],
    ]
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    target.chmod(0o600)


def default_service(server_name: str = "pqc-gateway.local", port: int = 8443) -> dict:
    return build_service(
        service_id="enterprise-pilot",
        adapter="http",
        listen_port=port,
        server_name=server_name,
        upstream="http://127.0.0.1:8080",
    )


def default_document(server_name: str = "pqc-gateway.local", port: int = 8443) -> dict:
    return {
        "schema_version": "4.0",
        "defaults": dict(ENTERPRISE_DEFAULTS),
        "services": [default_service(server_name, port)],
    }


def initialize(root: str | Path, scan_root: str | Path, *, server_name: str = "pqc-gateway.local",
               port: int = 8443, force: bool = False) -> dict:
    project = Path(root).resolve()
    scan = Path(scan_root).expanduser().resolve()
    if not scan.exists() or not scan.is_dir():
        raise ValueError(
            f"scan root is not an existing host directory: {scan}; "
            "choose an existing application directory or create it before initialization"
        )
    env_path = project / DEFAULT_ENV
    config_path = project / DEFAULT_CONFIG
    existing = load_env(env_path)
    values: dict[str, object] = {
        "GRAFANA_ADMIN_PASSWORD": existing.get("GRAFANA_ADMIN_PASSWORD") or secrets.token_hex(16),
        "MANAGER_API_TOKEN": existing.get("MANAGER_API_TOKEN") or secrets.token_hex(32),
        "PQ_CONFIG_SIGNING_KEY": existing.get("PQ_CONFIG_SIGNING_KEY") or secrets.token_hex(32),
        "PQ_EBPF_ENABLED": existing.get("PQ_EBPF_ENABLED", "0"),
        "PQ_GATEWAY_IMAGE": "pq-migration-gateway-pq-gateway:3.7",
        "PQ_MANAGER_API_BIND": existing.get("PQ_MANAGER_API_BIND", "127.0.0.1"),
        "PQ_MANAGER_API_URL": existing.get("PQ_MANAGER_API_URL", "http://127.0.0.1:18080"),
        "PQ_PROCESS_SCAN_ENABLED": existing.get("PQ_PROCESS_SCAN_ENABLED", "0"),
        "PQ_RUNTIME_GID": os.getgid() if hasattr(os, "getgid") else 1000,
        "PQ_RUNTIME_UID": os.getuid() if hasattr(os, "getuid") else 1000,
        "PQ_SCAN_HOST_ROOT": str(scan),
        "RUNTIME_AGENT_TOKEN": existing.get("RUNTIME_AGENT_TOKEN") or secrets.token_hex(32),
    }
    if force or not env_path.exists():
        write_env(env_path, values)
    else:
        # Updating the authorized root is safe and does not rotate existing secrets.
        values.update(existing)
        values["PQ_SCAN_HOST_ROOT"] = str(scan)
        values["PQ_GATEWAY_IMAGE"] = "pq-migration-gateway-pq-gateway:3.7"
        write_env(env_path, values)
    if force or not config_path.exists():
        config_path.parent.mkdir(parents=True, exist_ok=True)
        document = default_document(server_name, port)
        normalize_config(document)
        config_path.write_text(json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    for relative in ("logs", "metrics", "scans", "control", "certs", "prometheus", "grafana", "runtime-agent"):
        (project / "runtime-data" / "enterprise" / relative).mkdir(parents=True, exist_ok=True)
    return {
        "environment": str(env_path),
        "config": str(config_path),
        "scan_root": str(scan),
        "server_name": server_name,
        "listen_port": port,
        "secrets_preserved": bool(existing),
    }


def build_service(*, service_id: str, adapter: str, listen_port: int, server_name: str,
                  upstream: str, listen_address: str = "0.0.0.0", client_auth: str = "off",
                  upstream_tls: bool | None = None, upstream_verify: str = "off",
                  upstream_sni: str = "", upstream_ca: str = "/etc/ssl/certs/ca-certificates.crt",
                  upstream_client_certificate: str = "", upstream_client_key: str = "") -> dict:
    if upstream_tls is None:
        upstream_tls = adapter == "http" and urlsplit(upstream).scheme == "https"
    if upstream_tls and upstream_verify == "off":
        upstream_verify = "required"
    return {
        "id": service_id,
        "adapter": adapter,
        "listen": {"address": listen_address, "port": int(listen_port), "server_name": server_name},
        "downstream_tls": {
            "mode": "compatibility",
            "groups": ["X25519MLKEM768", "X25519"],
            "client_auth": client_auth,
            "certificate": "/etc/pq-gateway/certs/server.crt",
            "private_key": {"provider": "file", "reference": "/etc/pq-gateway/certs/server.key"},
            "client_ca": "/etc/pq-gateway/certs/ca.crt",
        },
        "upstream": {
            "address": upstream,
            "tls": {
                "enabled": bool(upstream_tls),
                "verify": upstream_verify if upstream_tls else "off",
                "sni": upstream_sni,
                "ca": upstream_ca,
                "client_identity": {
                    "certificate": upstream_client_certificate,
                    "private_key": {"provider": "file", "reference": upstream_client_key},
                },
            },
        },
        "timeouts": {"connect": "5s", "send": "60s", "read": "60s"},
        "rollout": {"policy": "fixed", "hybrid_percentage": 100, "fallback_allowed": True},
        "audit": {"enabled": True},
        "protocol_options": {},
    }


def upsert_service(config_path: str | Path, service: dict) -> dict:
    path = Path(config_path)
    document = json.loads(path.read_text(encoding="utf-8")) if path.exists() else default_document()
    services = list(document.get("services", []))
    if len(services) == 1 and services[0].get("id") == "enterprise-pilot" and service.get("id") != "enterprise-pilot":
        services = []
    services = [item for item in services if item.get("id") != service.get("id")]
    services.append(service)
    document["services"] = services
    canonical = normalize_config(document)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(canonical, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {"config": str(path), "service": service["id"], "services": len(canonical["services"]), "validated": True}


def redacted_status(root: str | Path) -> dict:
    project = Path(root).resolve()
    env_path = project / DEFAULT_ENV
    config_path = project / DEFAULT_CONFIG
    values = load_env(env_path)
    document = json.loads(config_path.read_text(encoding="utf-8")) if config_path.exists() else {"services": []}
    return {
        "environment": str(env_path),
        "configured": env_path.exists() and config_path.exists(),
        "scan_root": values.get("PQ_SCAN_HOST_ROOT", ""),
        "image": values.get("PQ_GATEWAY_IMAGE", ""),
        "services": [
            {"id": item.get("id"), "adapter": item.get("adapter"), "listen": item.get("listen"), "upstream": item.get("upstream", {}).get("address")}
            for item in document.get("services", [])
        ],
    }
